---
# ============================================
# Rust 
# ============================================
- name: "Rust | Dependencies"
  pacman:
      name:
          - curl
          - gcc
      state: present
